### ISSUE TITLE
Add new scoping features

### ISSUE THREAD

**Issue by wursttheke** [chrismccord/sync_example#6]
I recognized you are currently only using the controller-style way of syncing partials in the example app. My suggestion is to drop that approach on the TodosController and embrace the model DSL on it. We can leave the syncing of Comments as is to have an example of both approaches. What do you think?

**Comment by chrismccord** [comment]
Sounds good to me. Honestly I view the DSL as "the future", but the screencast shows the original controller way so it might be nice to include both examples.
